# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Подисчик', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
